language: go

sudo: false

go:
  - 1.13.x

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.24.0/install.sh | sh -s -- -b $GOPATH/bin v1.24.0

script:
  - golangci-lint run -c .golangci.yml
  - go test ./... -covermode count -coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash) -cF unittests
  - make intergrationtest
  - bash <(curl -s https://codecov.io/bash) -cF integration -f test_output/http_cache_test_coverage.out