language: go
sudo: false
go:
  - 1.13.x

script:
  - go test ./... -covermode count -coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash) -cF unittests
  - make intergrationtest
  - bash <(curl -s https://codecov.io/bash) -cF integration -f test_output/http_cache_test_coverage.out